Bloqueo/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('bloqueoApp/', include('bloqueoApp.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bloqueoApp/urls.py
from django.urls import path

from . import views, servicios

app_name = 'bloqueoApp'
urlpatterns = [
    #ejemplo para acceder vía url: /bloqueoApp
    path('', views.IndexView.as_view(), name='index'),
    # ejemplo para acceder vía url: /bloqueoApp/5/
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    # ejemplo para acceder vía url: /bloqueoApp/5/results/
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    # ejemplo para acceder vía url: /bloqueoApp/5/vote/
    path('<int:question_id>/vote/', views.vote, name='vote'),

    path('<int:pk>/detalle_estacion_bloqueo/', views.EstacionBloqueoDetailView.as_view(), name='detalle_estacion_bloqueo'),

    #path('<int:pk>/dispositivo/', views.DispositivoView.as_view(), name='dispositivo'),

    #path('<int:pk>/trabajador/', views.TrabajadorView.as_view(), name='trabajador'),
    path('trabajadores/', views.TrabajadorView.as_view(), name='trabajadores'),

    path('<int:trabajador_id>/trabajadorTarjeta/', views.TrabajadorTarjetaView, name='trabajadorTarjeta'),

    path('<int:trabajador_id>/<int:estacion_id>/trabajadorDetalle/', views.TrabajadorDetalleView, name='trabajadorDetalle'),

    path('<int:trabajador_id>/<int:estacion_id>/trabajadorRegistro/', views.TrabajadorRegistroView, name='trabajadorRegistro'),

    path('<int:pk>/departamento/', views.DepartamentoView.as_view(), name='departamento'),

    path('listado_trabajadores_dispositivo/', views.DispositivoView.as_view(), name='listado_trabajadores_dispositivo'),

    #path('listado_trabajadores_estacion/', views.EstacionBloqueoListView.as_view(), name='listado_trabajadores_estacion'),
    path('', views.IndexView.as_view(), name='listado_trabajadores_estacion'),

    path('trabajadores_sin_huella/', servicios.listarTrabajadorBloqueo, name='trabajadores_sin_huella'),
    path('registrar_usuario_dispositivo/', servicios.registrarUsuarioDispositivo, name='registrar_usuario_dispositivo'),
    path('bloquear_trabajador_dispositivo/', servicios.bloquearTrabajadorDispositivo, name='bloquear_trabajador_dispositivo'),
    path('estado_estacion/', servicios.getEstadoEstacion, name='estado_estacion'),
    path('registrar_responsable/', servicios.registrarResponsables, name='registrar_responsables'),
    path('limpiar/',servicios.limpiar,name='limpiar'),
    path('getResponsables/',servicios.getResponsables,name='get-responsables'),
    path('getTrabajadores/',servicios.getTrabajadore,name='get-trabajadores'),
]   

bloqueoApp/models.py
import datetime
from datetime import datetime

from django.db import models
from django.utils import timezone
from enum import Enum
from django import forms

# Create your models here.

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    
    def __str__(self):
        return self.question_text
    
    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    def __str__(self):
        return self.choice_text

class Departamento(models.Model):
    name = models.CharField(max_length=200)
    
    def __str__(self):
        return self.name

class Trabajador(models.Model):
    name = models.CharField(max_length=200)
    departamento = models.ForeignKey(Departamento, on_delete=models.CASCADE)
    celular = models.CharField(max_length=200, default="403645")
    codigo = models.CharField(max_length=200, default="123456")
    dni = models.CharField(max_length=200, default="36192398")
    emergencyPhone = models.CharField(max_length=200, default="462877")
    tiempo = models.TimeField('Hora de Ingreso')
    image = models.ImageField(upload_to='profile_image', blank=True)
    rol = models.BooleanField(default = False)
    def __str__(self):
        return self.name

class EstacionBloqueo(models.Model):
    name = models.CharField(max_length=200)
    # responsable = models.OneToOneField(
    #     Trabajador,
    #     on_delete=models.CASCADE,
    #     primary_key=True,
    # )
    #responsable = models.ForeignKey(Trabajador, on_delete=models.CASCADE)
    creation_date = models.DateTimeField('date created')
    PENDIENTE_BLOQUEO = 1
    BLOQUEADO = 2
    DESBLOQUEADO = 3
    STATES = (
        (PENDIENTE_BLOQUEO, 'Pendiente de Bloqueo'),
        (BLOQUEADO, 'Bloqueado'),
        (DESBLOQUEADO, 'Desbloqueado'),
    )
    state = models.IntegerField(choices=STATES, default=PENDIENTE_BLOQUEO)
    responsableState = models.IntegerField(choices=STATES, default=PENDIENTE_BLOQUEO)
    
    def __str__(self):
        return self.name

    def was_published_recently(self):
        return self.creation_date >= timezone.now() - datetime.timedelta(days=1)
    
    def __int__(self):
        return self.state

class Dispositivo(models.Model):
    estacionBloqueo = models.OneToOneField(
        EstacionBloqueo,
        on_delete=models.CASCADE,
        primary_key=True,
    )
    name = models.CharField(max_length=200)
    
    def __str__(self):
        return self.name



class DispositivoTrabajador(models.Model):
    trabajador = models.ForeignKey(Trabajador, on_delete=models.CASCADE, related_name="dispositivo_trabajador")
    dispositivo= models.ForeignKey(Dispositivo, on_delete=models.CASCADE)
    name = models.CharField(max_length=200, default='Dispositivo Trabajador')
    indice_trabajador = models.IntegerField(default=0)
    class Meta:
        ordering = ["dispositivo"]
    

class EstacionTrabajador(models.Model):
    trabajador = models.ForeignKey(Trabajador, on_delete=models.CASCADE, related_name="estacion_trabajador")
    estacion_bloqueo = models.ForeignKey(EstacionBloqueo, on_delete=models.CASCADE, related_name="estacion_trabajador" )
    name = models.CharField(max_length=200, default='Dispositivo Trabajador')
    PENDIENTE_BLOQUEO = 1
    BLOQUEADO = 2
    DESBLOQUEADO = 3
    STATES = (
        (PENDIENTE_BLOQUEO, 'Pendiente de Bloqueo'),
        (BLOQUEADO, 'Bloqueado'),
        (DESBLOQUEADO, 'Desbloqueado'),
    )
    state = models.IntegerField(choices=STATES, default=PENDIENTE_BLOQUEO)
    dateBloqueo = models.DateTimeField('Fecha Bloqueo', default=datetime.now, blank=True)
    dateDesbloqueo = models.DateTimeField('Fecha Desbloqueo', default=datetime.now, blank=True)
    
    def was_published_recently(self):
        return self.creation_date >= timezone.now() - datetime.timedelta(days=1)

bloqueoApp/views.py
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.template import RequestContext
from django.template.loader import get_template
from django.views import generic
from django.views.generic.base import View
from .models import Choice, Question, EstacionBloqueo, Dispositivo, Trabajador, Departamento, DispositivoTrabajador, EstacionTrabajador
from django.db.models import F, Count
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from datetime import datetime
# Create your views here.

# class IndexView(generic.ListView):
#     template_name = 'bloqueoApp/index.html'
#     context_object_name = 'latest_question_list'

#     def get_queryset(self):
#         """Return the last five published questions."""
#         return Question.objects.order_by('-pub_date')[:5]

class EstacionBloqueoDetailView(generic.DetailView):
    model = EstacionBloqueo
    template_name = 'bloqueoApp/detalle_estacion_bloqueo.html'

class IndexView(generic.ListView):
    model = EstacionBloqueo
    template_name = 'bloqueoApp/listado_trabajadores_dispositivo.html'
    context_object_name = 'dispositivo_list'

class DispositivoView(generic.ListView):
    model = Dispositivo
    #template_name = 'bloqueoApp/dispositivo.html'
    template_name = 'bloqueoApp/listado_trabajadores_dispositivo.html'
    context_object_name = 'dispositivo_list'


class TrabajadorView(generic.ListView):
    model = Trabajador
    template_name = ('bloqueoApp/trabajadores.html')

    context_object_name = 'trabajadores_list'
    paginate_by = 1


def TrabajadorTarjetaView(request, trabajador_id):
    trabajador = get_object_or_404(Trabajador, pk=trabajador_id)
    print(trabajador_id)
    return render (request,'bloqueoApp/trabajadorTarjeta.html', {'trabajador':trabajador})

def TrabajadorDetalleView(request, trabajador_id, estacion_id):
    trabajador = get_object_or_404(Trabajador, pk=trabajador_id)
    estacion = get_object_or_404(EstacionBloqueo, pk=estacion_id)
    responsables = estacion.estacion_trabajador.filter(trabajador__rol = 1) 
    print(trabajador)
    print(estacion)
    print(responsables)
    context = {
        'trabajador':trabajador,
        'responsables':responsables
    }
    return render(request, 'bloqueoApp/trabajadorDetalle.html', context)
    #return render (request,'bloqueoApp/trabajadorDetalle.html', {'trabajador':trabajador}, {'responsables':responsables})
    

def TrabajadorRegistroView(request, trabajador_id, estacion_id):
    trabajador = get_object_or_404(Trabajador, pk=trabajador_id)
    estacion = get_object_or_404(EstacionTrabajador, pk=estacion_id)
    #responsables = estacion.trabajador.filter(trabajador__rol = 1) 
    print(trabajador)
    print(estacion.dateDesbloqueo)
    context = {
        'trabajador':trabajador,
        'estacion':estacion
    }
    return render(request, 'bloqueoApp/trabajadorRegistro.html', context)


class DepartamentoView(generic.DetailView):
    model = Departamento
    template_name = 'bloqueoApp/departamento_detail.html'


class DispositivoTrabajadorView(generic.ListView):
    model = DispositivoTrabajador
    #template_name = 'bloqueoApp/listado_trabajadores_dispositivo.html'
    context_object_name = 'dispositivo_trabajador_list'


class DetailView(generic.DetailView):
    model = Question
    template_name = 'bloqueoApp/detail.html'


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'bloqueoApp/results.html'


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        print("CARLOS")    
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        print("PEDRO")    
        # Redisplay the question voting form.
        return render(request, 'bloqueoApp/detail.html', {
             'question': question,
             'error_message': "No ha seleccionado ninguna opción.",
        })
    else:
        #selected_choice = Question.objects.select_for_update().get(pk=question_id)
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('bloqueoApp:results', args=(question.id,)))

# def index(request):
#     latest_question_list = Question.objects.order_by('-pub_date')[:5]
#     template = loader.get_template('bloqueoApp/index.html')
#     context = { 
#                 'latest_question_list': latest_question_list 
#               }
#     return HttpResponse(template.render(context, request))

# def detail(request, question_id):
#     question = Question.objects.get(pk=question_id)
#     template = loader.get_template('bloqueoApp/detail.html')
#     return HttpResponse(template.render({'question': question}, request))

# def results(request, question_id):
#     response = "You're looking at the results of question %s."
#     return HttpResponse(response % question_id)

# def vote(request, question_id):
#     question = get_object_or_404(Question, pk=question_id)
#     try:
#         print("CARLOS")    
#         selected_choice = question.choice_set.get(pk=request.POST['choice'])
#     except (KeyError, Choice.DoesNotExist):
#         print("PEDRO")    
#         # Redisplay the question voting form.
#         return render(request, 'bloqueoApp/detail.html', {
#              'question': question,
#              'error_message': "No ha seleccionado ninguna opción.",
#         })
#     else:
#         #selected_choice = Question.objects.select_for_update().get(pk=question_id)
#         selected_choice.votes += 1
#         selected_choice.save()
#         # Always return an HttpResponseRedirect after successfully dealing
#         # with POST data. This prevents data from being posted twice if a
#         # user hits the Back button.
#         return HttpResponseRedirect(reverse('bloqueoApp:results', args=(question.id,)))

# def results(request, question_id):
#     question = get_object_or_404(Question, pk=question_id)
#     return render(request, 'bloqueoApp/results.html', {'question': question})

bloqueoApp/templates/bloqueoApp/departamento_detail.html

{% block body %}
<h1>{{departamento.name}}</h1>
{% endblock %}

bloqueoApp/templates/bloqueoApp/detail.html
<h1>{{ question.question_text }}</h1>

{% if error_message %}
    <p><strong>{{ error_message }}</strong></p>
{% endif %}

<form action="{% url 'bloqueoApp:vote' question.id %}" method="post">
    {% csrf_token %}
        {% for choice in question.choice_set.all %}
            <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
            <label for="choice{{ forloop.counter }}">
                {{ choice.choice_text }}
            </label>
            <br>
        {% endfor %}
    <input type="submit" value="Vote">
</form>

<!-- <ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }}</li>
{% endfor %}
</ul> -->

bloqueoApp/templates/bloqueoApp/detalle_estacion_bloqueo.html
{% extends "base_generic.html" %}

{% block content %}
    <style>
        th#titulos{
            /*background-color: coral;*/
            /*background:#292929;*/
            background:#292929;
            color:#fff;
            /*box-shadow: 0px 2px 10px 1px rgba(57,172,235,0.7);*/
        }

        th#titulos:hover {
            background:#30d9a4; color:#fff;
        }

        tr#encabezado{
            background:rgba(0, 0, 0, 0.5);
            color:#fff;
            /*box-shadow: 0px 2px 10px 1px rgba(57,172,235,0.9);*/
            font-weight: bold;
        }

        tr#encabezado:hover {
            background:#30d9a4; color:#fff;
        }

        div#lideres{
            background-color: bisque;
            position: absolute;
            /*margin-top: -5px;*/
            width: 97%;
        }

        div#responsables{
            background-color: bisque;
            position: absolute;
            margin-top: 100px;
            width: 97%;
        }

        tr#estacion{
            line-height:8;
            /*padding-bottom: 7;*/
            /*line-height:70%;*/
            /*padding-bottom: 3px;*/
            /*padding-top: 10px;*/
        }

        .grupos{
            display: block;
            margin-left: 25px;
            width: 100%;
            height: 500px;
            margin-bottom: 60px;
            margin-top: 10px;
        }

        .button_fullwidth{
            /*background-color:rgba(0, 0, 0, 0.5);*/
            /*background-color:rgba(48, 217, 164, 1);*/
            /*margin-top: 80px;*/
        }
        

        a:link {
            color: rgba(0, 0, 0, 0.8);
        }

        a#trabajador-clicked{
            color: rgba(0, 0, 0, 0.8);
        }

        ul#listado{
            float: left;
        }

        /*table#centerMiddle{
            margin-left:10%;
        }*/

        table, td, th {
            border: 0.1px solid black;
            /*font-size: 10px;*/
        }
        
        .table1 {
            /*border-collapse: separate;*/
            width: 100%;
            /*border-spacing: 15px;*/
        }

        @media all and (min-width: 569px) and (max-width: 1023px){
            table#centerMiddle{
                margin-left:0%;
            }

            div#lideres{
                width: 96%;
            }
    
            div#responsables{
                width: 96%;
            }
        }

        @media all and (min-width: 0px) and (max-width: 568px){

            .container {
                width: auto;
                min-width: 0;
                display: table;
            }

            .row {
                margin-left: -32px;
            }

            *, ::after, ::before {
                box-sizing: unset;
            }

            .button_fullwidth {
                width: 92.5%;
            }

            tr#estacion{
                padding-top: 10px;   
            }

            div#lideres{
                width: 94%;
                /*margin-top: 20px;*/
            }
    
            td#responsables{
                /*margin-top: 165px;*/
                width: 100%;
            }

            tr#responsables2{
                /*margin-top: 165px;*/
                width: 100%;
            }

            #templateColumns{
                width:100% !important;
            }

            .templateColumnContainer{
                display:block !important;
                width:100% !important;
            }

            .columnImage{
                height:auto !important;
                max-width:480px !important;
                width:100% !important;
            }

            .leftColumnContent{
                /*font-size:16px !important;*/
                line-height:125% !important;
            }

            .rightColumnContent{
                font-size:16px !important;
                line-height:125% !important;
            }

            .imageColumn{
                font-size:16px !important;
                line-height:125% !important;
            }

            table, td, th {
                font-size: 11px;
            }
        }
    </style>


    <div class="hidden">
        <input style="display:none;" value="{{estacionbloqueo.pk}}" id="id_estacionbloqueo">
    </div>

    <div class="container center-block" id="contenedor">
        <div class="row  center-block" >
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 grupos">
                
                <button type="button" class="button_fullwidth"><h1>{{ estacionbloqueo.name }}</h1></button>
                <table class="table1" id="centerMiddle">
                    <tr>
                        <th colspan="5" id="titulos" class="text-center">
                            Líderes de Bloqueo
                        </th>
                    </tr>
                    <tr id="encabezado">
                        <td class="text-center">
                            Responsable
                        </td>
                        <td class="text-center">
                            Estado
                        </td>
                        <td class="text-center">
                            Tarjeta
                        </td>
                        <td class="text-center">
                            Identificación
                        </td>
                        <td class="text-center">
                            Registro
                        </td>
                    </tr>

                    {% for r in estacionbloqueo.estacion_trabajador.all %}
                        {% if  r.trabajador.rol %}
                            {% if r.state != 1 %}
                            
                            <tr width="100%" class="text-center">
                                <td align="center" valign="center" width="50%" class="leftColumnContent">
                                    {{ r.trabajador }}
                                </td>
                                <td align="center" width="50%" class="rightColumnContent text-center">
                                    {% if r.state == 1 %}
                                    <button class="btn btn-warning">Pendiente de Bloqueo</button>
                                    {% elif r.state == 2 %}
                                    <i class="fa fa-lock" style="color:red;font-size:35px;" aria-hidden="true"></i>
                                    {% elif r.state == 3 %}
                                    <i class="fa fa-unlock" style="color: green;font-size:35px;" aria-hidden="true"></i>
                                    {% else %}
                                    No se ha seleccionado estado
                                    {% endif %}
                                </td>
                                <td valign="center" width="50%" class="imageColumn">
                                    <a href="{{r.trabajador.id}}/trabajadorTarjeta/" id="trabajador-clicked">
                                        {% if r.trabajador.image is not empty %}
                                        <img src="../../media/imagenTarjeta.PNG" alt="Foto" width="50" height="50"/>
                                        {% endif %}
                                    </a>
                                </td>
                                <td valign="center" width="50%" class="imageColumn">
                                    <a href="{{r.trabajador.id}}/{{estacionbloqueo.id}}/trabajadorDetalle/" id="trabajador-clicked">
                                        {% if r.trabajador.image is not empty %}
                                        <img src="{{r.trabajador.image.url}}" alt="Foto" width="50" height="50"/>
                                        {% endif %}
                                    </a>
                                </td>
                                <td width="50%" class="imageColumn">
                                    <a href="{{r.trabajador.id}}/{{r.trabajador.id}}/trabajadorRegistro/" id="trabajador-clicked">
                                        <i class="fa fa-file-text-o" style="font-size:35px;"></i>
                                    </a>
                                </td>                      
                            </tr>
                            {% endif %}
                        {% endif %}
                    {% endfor %}
                    <tr>
                        <th colspan="5" id="titulos" class="text-center">
                            Responsables de Bloqueo Grupal
                        </th>
                    </tr>
                    <tr id="encabezado">
                        <td class="text-center">
                            Responsable
                        </td>
                        <td class="text-center">
                            Estado
                        </td>
                        <td class="text-center">
                            Tarjeta
                        </td>
                        <td class="text-center">
                            Identificación
                        </td>
                        <td class="text-center">
                            Registro
                        </td>
                    </tr>
                    {%for e in estacionbloqueo.estacion_trabajador.all%}
                        {% if  e.trabajador.rol == 0 %}
                            {% if e.state != 1 %}
                        
                        
                            <tr width="100%" class="text-center">
                                <td align="center" valign="center" width="50%" class="leftColumnContent">
                                    {{e.trabajador.name}}
                                </td>
                                <td align="center" width="50%" class="rightColumnContent text-center">
                                    {% if e.state == 1 %}
                                    <button class="btn btn-warning">Pendiente de Bloqueo</button>
                                    {% elif e.state == 2 %}
                                    <!--<button class="btn btn-danger">Bloqueado</button>-->
                                    <i class="fa fa-lock" style="color:red;font-size:35px;" aria-hidden="true"></i>
                                    {% elif e.state == 3 %}
                                    <!--<button class="btn btn-success">Desbloqueado</button>-->
                                    <i class="fa fa-unlock" style="color:green;font-size:35px;" aria-hidden="true"></i>
                                    {% else %}
                                    No se ha seleccionado estado
                                    {% endif %}
                                </td>
                                <td valign="center" width="50%" class="imageColumn">
                                    <a href="{{e.trabajador.id}}/trabajadorTarjeta/" id="trabajador-clicked">
                                        {% if e.trabajador.image is not empty %}
                                        <img src="../../media/imagenTarjeta.PNG" alt="Foto" width="50" height="50"/>
                                        {% endif %}
                                    </a>
                                </td>
                                <td valign="center" width="50%" class="imageColumn">
                                    <a href="{{e.trabajador.id}}/{{estacionbloqueo.id}}/trabajadorDetalle/" id="trabajador-clicked">
                                        {% if e.trabajador.image is not empty %}
                                        <img src="{{e.trabajador.image.url}}" alt="Foto" width="50" height="50"/>
                                        {% endif %}
                                    </a>
                                </td>
                                <td width="50%" class="imageColumn">
                                    <a href="{{e.trabajador.id}}/{{e.trabajador.id}}/trabajadorRegistro/" id="trabajador-clicked">
                                        <i class="fa fa-file-text-o" style="font-size:35px;"></i>
                                    </a>
                                </td>
                            </tr>
                            {% endif %}
                        {% endif %}
                    {%endfor%}
                </table>
            </div>
        </div>    
    </div>

    {% block javascript %}
        <script>
            window.setInterval(function(){
                var url = "{% url 'bloqueoApp:detalle_estacion_bloqueo' 0 %}"
                var id = $("#id_estacionbloqueo").val();
                console.log(id);
                url = url.replace("/0", "/"+id); 
                ($("#centerMiddle" ).load( url + "#centerMiddle table" ));
            },1000);
        </script>
    {% endblock %}

{% endblock content%}





bloqueoApp/templates/bloqueoApp/dispositivo.html
<h1>{{ dispositivo.name }}</h1>
<h1>{{ dispositivo.estacionBloqueo.name }}</h1>

bloqueoApp/templates/bloqueoApp/index.html
{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li><a href="{% url 'bloqueoApp:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No Questions are available.</p>
{% endif %}

bloqueoApp/templates/bloqueoApp/limpiar.html
{% extends 'admin/change_list.html' %}

{% block object-tools-items %}
{{ block.super }}
<li>
	<a href="{% url 'bloqueoApp:limpiar' %}" class="">Limpiar estaciones</a>
</li>
{% endblock %}

bloqueoApp/templates/bloqueoApp/listado_trabajadores_dispositivo.html
{% extends "base_generic.html" %}

{% block cabecera %}
    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4">
        <a id="marca" href={% url "bloqueoApp:listado_trabajadores_estacion" %}>TecBloqueo</a>
    </div>

    <nav class="col-lg-8 col-md-8 col-sm-8 col-xs-8" id="botonera">
        <a href={% url "bloqueoApp:trabajadores" %} class="button_top" id="login_top">Ver Empleados</a>
    </nav>
{% endblock cabecera %}

{% block content %}

<style>
    .grupos{
        display: block;
        /*argin-left: 25px;*/
        width: 100%;
        height: 500px;
        margin-bottom: 60px;
        margin-top: 10px;
        text-align: center;
    }

    iframe#someFrame{
        border-width: 0px;
        border-style: inset;
        border-color: initial;
        border-image: initial;
        margin-top: -20px;
    }

    @media all and (max-width: 599px){
        .dispositivo-clic{
            margin-left: 5px;
        }

        div#copy_right{
            margin-top: -70px;
        }
    }
    
</style>
<!--<section>-->
        <!--<div class="container">-->
            <!--<div class="row" > -->
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 grupos center-block">
                    {% if dispositivo_list %}
                    <select name="" id="dispositivo" class="form-control dispositivo-clic" style="width:100%;">
                            <option value="0">-Seleccione una Estación-</option>
                        {% for d in dispositivo_list %}
                            <option class="dropdown-item" value="{{ d.pk }}" >{{ d }}</option>
                        {% endfor %}
                    </select>
                    <br>
                    <iframe name="someFrame" id="someFrame" height=100% width="100%"></iframe>
                    {%else%}
                        <h1>no hay</h1>
                    {% endif %}
                </div>
            <!--</div>-->
        <!--</div> End container -->
<!--</section>-->

{% endblock content %}

{% block javascript %}
    <script>   
        $(document).ready(function() {
            var dispositivoSel = $("#dispositivo option:selected");
            console.log(dispositivoSel.select);
            
            $("#dispositivo").on('change', function () {        
                var url = "{% url 'bloqueoApp:detalle_estacion_bloqueo' 0 %}"
                var b = $("#dispositivo option:selected").val()
                url = url.replace("/0", "/"+b)

                $.get(url)
                .done(response => {
                    document.getElementById("someFrame").html = response;
                    $("#someFrame").attr("srcdoc", response);
                })
            });
        });     
    </script>
{%endblock%}

{% block pie %}
    <div class="col align-self-end" id="copy_right">
        © 2018 - Evolution Soluciones Digitales S.R.L.
    </div>
{% endblock pie %}
    

bloqueoApp/templates/bloqueoApp/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'bloqueoApp:detail' question.id %}">Desea volver a Votar?</a>